// Practice problem 2.18

// In Chapter 3, we will look at listings generated by a disassembler, a program that converts an executable program file 
// back to a more readable ASCII form. These files contain many hexadecimal numbers, typically representing values in 
// two’s-complement form. Being able to recognise these numbers and understand their significance (for example, whether 
// they are negative or positive) is an important skill. 

// For the lines labeled A–I (on the right) in the following listing, convert the hexadecimal values (in 32-bit 
// two’s-complement form) shown to the right of the instruction names (sub, mov, and add) into their decimal equivalents:

// A = 440
// B = 20
// C = -424
// D = -396
// E = 68
// F = -312
// G = 16
// H = 12
// I = -276 
// J = 32