/* Complete the macro SET_BIT to set the bit in position pos, the macro CLEAR_BIT
to clear the bit in position pos, and the macro CHECK_BIT to display the value of the bit in
position pos. Write a program that reads an integer and a bit position and tests the opera-
tion of these three macros.*/

#define SET_BIT(a, pos) ...
#define CLEAR_BIT(a, pos) ...
#define CHECK_BIT(a, pos) ...